### PR TITLE
basic Web version

### PR DESCRIPTION
**Pull request by sxn**
After delaying it a bunch of times, here's a very rough version of a 'working' game. There are still a bunch of things that I'd like to do (such as showing player names, making them configurable, less ugly design, showing a result screen when the game ends in a draw etc), maybe I'll get to do them at the next meetup. :)

### CODE REVIEW

**Comment by wwwdata** [comment]
cool, just tested it, works fine for me :) You just have to fix some conflicts to it can be merged

**Comment by adamterlson** [comment]
Boo conflicts.  Can you fix those Sorin and update the PR or would you like me to? :)

**Comment by sxn** [comment]
I'll fix them :)

**Comment by sxn** [comment]
...apparently I can't fix them, for some reason. Could you please do it, if it's not too much?

**Comment by adamterlson** [comment]
Done.  Thanks!

**Pull request merged**
