### PR TITLE
this pull request is still open! :P

### PR DESCRIPTION
**Pull request by wwwdata**
I connected way too many components (3) to the state and unnecessarily excluded way too much stuff into their own javascript files but it works :smile: 

It all comes down to creating a new board and playing with winner determination. Including the `game.js` in the reducers is totally fine in my opinion because they already are pure  functions which is what reducers are, right?

### CODE REVIEW

**Comment by adamterlson** [comment]
Awesome.  I made a couple comments on things but I can just merge it in and touch stuff up.  Thanks for helping out!

**Comment by wwwdata** [comment]
Wait with the merge until I fix stuff please :)

**Comment by adamterlson** [comment]
> So, if I put in the same old state and the same action, it will always calculate the same next state, so I am not violating anything?

So I thought more about your above comment, and I totally don't know for certain what way is "right", but I've been thinking more about how things would be done with a server-side computation of state (that is, if the moves, game creation, etc were in fact made on the server-side).  In such a situation, the API call cannot be made in the reducer, it has to be done in the action creator which then gets the resultant game state from the server and dispatches an action (with the help of redux-thunk, perhaps called "UPDATE_BOARD") with all the information the reducer needs to update the state of the board on the client.  In this case, it's the entire new board state only.

Now, remove the AJAX/API call element from things and I think you arrive at the conclusion that all the calls to game.js or whatever else should probably _still_ happen in the action creators and only the updated board should be sent to the reducer.

I agree it's perhaps a bit odd that the action creator that makes a board update must be passed in the player and current board state....  I can't think of a good way around that, but I think if you redefine "play" to "update_board" it makes _a bit_ more sense...

Also, I'm okay with passing in the player because in a game where player don't actually take turns so nicely, each update will need to be told which player performed the action. 

Good discussion!

**Comment by wwwdata** [comment]
hm, yes If the game logic would be server side, you are right. But this is not the case. 

Also if this would be a real game and there are at least 2 clients, because tic tac toe is a 2 player game, the server would also need to store the game board state, right? So basically we would only have to submit the next turn of player A/B to the server and the server would then return a new updated game board to all the (2) clients connected to it. In that case, the call to the server would happen in the action creator, and once there is a result it will be pushed into the redux store via the reducer like you described, but it's still not necessary to push the whole board to the server. It would also be stupid in a real world to do that, because you could easily cheat! :smile: 

Hm, so maybe we should treat the game-server as a real server with it's own state in our example and do the call synchronously in the action creator? This would be closest to a real world example, right?

**Comment by adamterlson** [comment]
> hm, yes If the game logic would be server side, you are right. But this is not the case.

Indeed, I was just thinking that whatever approach we take should follow the same patterns so that when it is the case (which I was thinking could be the topic of a future meetup), we don't need to go changing around a bunch of stuff.

> It would also be stupid in a real world to do that, because you could easily cheat!

You're definitely right about that!  Good point.  What FPS games do is validation of new state updates (called [Backwards Reconciliation](https://www.reddit.com/r/truegaming/comments/2ruqba/advances_in_fps_netcode/)) to reduce lag.  The client requests a certain update and then that change is verified on the server as being valid, rather than necessarily doing all the computation of the update entirely on the server.  Anyway, that's besides the point except to say the client computing the next state can be valid as long as the server is sure to do verification!

So I found some "prior art" related to Tic Tac Toe in Redux and found [this](https://github.com/hieudt/redux-tic-tac-toe/blob/master/src/reducers/tictactoe.js).  It seems here the author has created an action for moving, and checks the win state using the previous board in the reducer and the player and coord from the action.  I'd be hesitant to create another state store.

So, here're my thoughts at the end of all this which I think is pretty close to your original approach:
1. PlayerActions.js Action creator: `move(player, coord)` dispatches action `PLAYER_MOVE` with properties `player` and `coord`.
2. Game.js Reducer: Calls into `game.js` library with previous board state coming from `state.board`, player from `action.player` and coord from `action.coord` to calculate the next state and returns that as the next board state.  
3. Create separate reducers for move count, current player, and board state.

So, the knowledge of previous board state is removed from action creators, and the reducer doesn't need to know about player alternating, it just makes the requested update.

Thoughts?! :D

**Comment by wwwdata** [comment]
that sounds good :)
sorry for the late response, holydays and stuff. I will clean up my code that it works in this way now!

**Comment by wwwdata** [comment]
wow this pr is still open, should this be merged?

**Comment by adamterlson** [comment]
Whoops

**Pull request merged**
